name: Caesar

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  code_quality:
    name: Code quality
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Install rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt

    - name: Install latest just release
      uses: taiki-e/install-action@just

    - name: Ensure `fmt` has been run
      run:  just fmt-check

    - name: Install Qt
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends --allow-unauthenticated \
          qt6-base-dev                                                          \
          qt6-declarative-dev

    - name: Run clippy
      run: just lint
      
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        target: x86_64-unknown-linux-gnu
    - name: Install Qt
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends --allow-unauthenticated \
          qt6-base-dev                                                          \
          qt6-declarative-dev
    - name: Build
      run: cargo build --release --locked
